ALTER TABLE Pret
ALTER COLUMN est_prolonge DROP DEFAULT;

ALTER TABLE Pret
ALTER COLUMN est_prolonge SET DATA TYPE BOOLEAN
USING est_prolonge::BOOLEAN;

ALTER TABLE Pret
ALTER COLUMN est_prolonge SET DEFAULT false;
